replicaCount: 1

image:
  repository: ghcr.io/upendra-manike/syntricdb
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080

config:
  bindAddress: "0.0.0.0"
  port: 8080
  authEnabled: true
  adminUser: "admin"
  adminPassword: "syntricdb_secret_pass"
  dataDir: "/var/lib/syntricdb/data"

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 20Gi

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
