apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "syntricdb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "syntricdb.name" . }}
    helm.sh/chart: {{ include "syntricdb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: {{ include "syntricdb.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "syntricdb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "syntricdb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http-api
          envFrom:
            - configMapRef:
                name: {{ include "syntricdb.fullname" . }}-config
            - secretRef:
                name: {{ include "syntricdb.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: syntricdb-storage
              mountPath: /var/lib/syntricdb
          livenessProbe:
            httpGet:
              path: /api/sql
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/sql
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: syntricdb-storage
      spec:
        accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
  {{- end }}
